CREATE TABLE exam_zenith.roles
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE exam_zenith.users
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE exam_zenith.user_role (
   USER_ID BIGINT NOT NULL,
   ROLE_ID BIGINT NOT NULL,
   PRIMARY KEY (USER_ID, ROLE_ID),
   FOREIGN KEY (USER_ID) REFERENCES users (ID),
   FOREIGN KEY (ROLE_ID) REFERENCES roles (ID)
);