  CREATE TABLE exam_zenith.courses
  (
  ID BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
  );

  CREATE TABLE exam_zenith.question_forms
  (
  ID BIGINT NOT NULL PRIMARY KEY,
  COURSE_ID BIGINT NOT NULL,
  FOREIGN KEY (COURSE_ID) REFERENCES exam_zenith.courses(ID) ON DELETE CASCADE
  );

  CREATE TABLE exam_zenith.questions
  (
  ID BIGINT NOT NULL PRIMARY KEY,
  QUESTION_FORM_ID BIGINT NOT NULL,
  QUESTION_TEXT VARCHAR(1000) NOT NULL,
  QUESTION_TYPE VARCHAR(20) NOT NULL CHECK(QUESTION_TYPE IN ('RADIO','CHECKBOX','TEXT')),
  FOREIGN KEY (QUESTION_FORM_ID) REFERENCES exam_zenith.question_forms (ID) ON DELETE CASCADE
  );

