--Only radio and checkbox
CREATE TABLE exam_zenith.answer_options
(
ID BIGINT PRIMARY KEY,
QUESTION_ID BIGINT NOT NULL,
OPTION_TEXT VARCHAR(1000) NOT NULL,
FOREIGN KEY (QUESTION_ID) REFERENCES exam_zenith.questions (ID) ON DELETE CASCADE
);


CREATE TABLE exam_zenith.student_answers
(
ID BIGINT PRIMARY KEY,
STUDENT_ID BIGINT NOT NULL,
QUESTION_ID BIGINT NOT NULL,
OPTION_ID BIGINT, --IF answer is radio or checkbox
TEXT_ANSWER TEXT, --IF answer is TEXT

FOREIGN KEY (STUDENT_ID) REFERENCES exam_zenith.users (ID) ON DELETE CASCADE,
FOREIGN KEY (QUESTION_ID) REFERENCES exam_zenith.questions (ID) ON DELETE CASCADE,
FOREIGN KEY (OPTION_ID) REFERENCES exam_zenith.answer_options (ID) ON DELETE CASCADE,

CHECK(
    (OPTION_ID IS NOT NULL AND TEXT_ANSWER IS NULL) OR
    (OPTION_ID IS NULL AND TEXT_ANSWER IS NOT NULL)
)
);

CREATE UNIQUE INDEX unique_single_answer_per_student
ON exam_zenith.student_answers(STUDENT_ID, QUESTION_ID)
WHERE OPTION_ID IS NOT NULL OR TEXT_ANSWER IS NOT NULL;


