CREATE TABLE exam_zenith.teacher_course
(
TEACHER_ID BIGINT NOT NULL,
COURSE_ID BIGINT NOT NULL,
PRIMARY KEY (TEACHER_ID, COURSE_ID),

FOREIGN KEY (TEACHER_ID) REFERENCES users (ID) ON DELETE CASCADE,
FOREIGN KEY (COURSE_ID) REFERENCES courses (ID) ON DELETE CASCADE
);

CREATE TABLE exam_zenith.student_course
(
STUDENT_ID BIGINT NOT NULL,
COURSE_ID BIGINT NOT NULL,
PRIMARY KEY (STUDENT_ID, COURSE_ID),

FOREIGN KEY (STUDENT_ID) REFERENCES users (ID) ON DELETE CASCADE,
FOREIGN KEY (COURSE_ID) REFERENCES courses (ID) ON DELETE CASCADE
);